// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoQfkQvQBqS3GI2ae1t1QrNFNHwRFwe-Q',
    appId: '1:68440423433:web:8301e31385c16f1932ccd8',
    messagingSenderId: '68440423433',
    projectId: 'e-blood-donor-bba43',
    authDomain: 'e-blood-donor-bba43.firebaseapp.com',
    storageBucket: 'e-blood-donor-bba43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALe1NZSLp402WaECr3PZxmDFAcwP8pueg',
    appId: '1:68440423433:android:4fb8e22658311e1d32ccd8',
    messagingSenderId: '68440423433',
    projectId: 'e-blood-donor-bba43',
    storageBucket: 'e-blood-donor-bba43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKzMbYJYNUVr38MRXHZvQnPDMIy7alHmQ',
    appId: '1:68440423433:ios:d33e9ebd2d6d6e4632ccd8',
    messagingSenderId: '68440423433',
    projectId: 'e-blood-donor-bba43',
    storageBucket: 'e-blood-donor-bba43.appspot.com',
    iosBundleId: 'com.example.eBloodDonor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKzMbYJYNUVr38MRXHZvQnPDMIy7alHmQ',
    appId: '1:68440423433:ios:5387e3a1ec52a49232ccd8',
    messagingSenderId: '68440423433',
    projectId: 'e-blood-donor-bba43',
    storageBucket: 'e-blood-donor-bba43.appspot.com',
    iosBundleId: 'com.example.eBloodDonor.RunnerTests',
  );
}
